### ISSUE TITLE
Ram usage

### ISSUE THREAD

**Issue by tonz134** [jojobii-arks/ot-ngs-log-observer#10]
It ate like 12gb of my ram in a minute of farming

**Comment by tonz134** [comment]
![Taskmgr_k3Y0o0RaC2](https://user-images.githubusercontent.com/10042287/231004166-350a906f-3cb2-4ccc-8098-e56e09a30f52.png)

**Comment by jojobii-arks** [comment]
Electron app moment 💀 (I'll look into this)

**Comment by jojobii-arks** [comment]
Gonna mark this as resolved by https://github.com/jojobii-arks/ngs-log-observer/commit/a0d1b910c71d14a25786cab37a9deb4dc4465aaf

I'll keep a look out if there's anything unusual. If it's still hogging 12GB, lmk.
